spring.application.name=BrowseCityAPI
spring.datasource.url=jdbc:${DATABASE_URL:postgresql://localhost:5431/browsecity}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:postgres123}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update