spring.application.name=BrowseCityAPI
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5431}/${POSTGRES_DB:browsecity}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:postgres123}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update